# Generated by Django 6.0.4 on 2026-04-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(default='📱', max_length=10, verbose_name='Эмодзи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки устройств',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон / Telegram')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('result', models.TextField(blank=True, verbose_name='Результат звонка')),
            ],
            options={
                'verbose_name': 'Заявка на обзвон',
                'verbose_name_plural': 'Заявки на обзвон',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Устройство')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Kayros', max_length=100, verbose_name='Название компании')),
                ('tagline', models.CharField(default='Профессиональный ремонт телефонов', max_length=200, verbose_name='Подзаголовок')),
                ('phone', models.CharField(default='+7 (999) 000-00-00', max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(default='г. Москва, ул. Примерная, д. 1', max_length=300, verbose_name='Адрес')),
                ('working_hours', models.CharField(default='Пн–Вс: 09:00 – 21:00', max_length=100, verbose_name='Часы работы')),
                ('telegram_bot_link', models.URLField(default='https://t.me/your_bot', verbose_name='Ссылка на Telegram-бот')),
                ('telegram_channel', models.URLField(blank=True, verbose_name='Telegram-канал')),
                ('about_text', models.TextField(default='Мы занимаемся ремонтом телефонов с 2015 года.', verbose_name='О нас (краткое)')),
                ('about_full_text', models.TextField(blank=True, verbose_name='О нас (полное)')),
                ('yandex_map_embed', models.TextField(blank=True, verbose_name='Код встраивания Яндекс.Карты')),
                ('google_map_embed', models.TextField(blank=True, verbose_name='Код встраивания Google Maps')),
                ('warranty_days', models.PositiveIntegerField(default=90, verbose_name='Гарантия (дней)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название модели')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_models', to='core.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель телефона',
                'verbose_name_plural': 'Модели телефонов',
                'ordering': ['brand__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepairService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Услуга')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Доп. описание')),
                ('price_from', models.PositiveIntegerField(verbose_name='Цена от (₽)')),
                ('price_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена до (₽)')),
                ('duration', models.CharField(default='1–2 часа', max_length=50, verbose_name='Срок ремонта')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.phonemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Услуга / позиция прайса',
                'verbose_name_plural': 'Услуги / прайс-лист',
                'ordering': ['phone_model__brand__order', 'phone_model__order', 'order', 'name'],
            },
        ),
    ]
