# Generated by Django 6.0.5 on 2026-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='emoji',
            field=models.CharField(default='📱', max_length=10, verbose_name='Эмодзи (alias)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='actual_address',
            field=models.TextField(blank=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='corr_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корр. счёт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='director_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО директора'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Печать'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp'),
        ),
    ]
