# Generated by Django 4.2.16 on 2026-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_emoji_sitesettings_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bot_deepseek_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='DeepSeek API Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bot_prompt',
            field=models.TextField(blank=True, default='Ты помощник сервисного центра по ремонту телефонов. Отвечай вежливо и кратко. Помогай клиентам узнать цены и записаться на ремонт.', verbose_name='Системный промпт бота'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Токен Telegram-бота'),
        ),
    ]
