# Generated by Django 4.2.16 on 2026-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_and_bot_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bot_ollama_model',
            field=models.CharField(blank=True, default='deepseek-r1:7b', help_text='Название модели в Ollama: deepseek-r1:7b, deepseek-r1:1.5b и т.д.', max_length=100, verbose_name='Ollama модель'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bot_ollama_url',
            field=models.CharField(blank=True, help_text='Например: http://localhost:11434/v1 — если хотите использовать локальную модель вместо DeepSeek API', max_length=200, verbose_name='Ollama URL (локальная модель)'),
        ),
    ]
