# Generated by Django 4.2.16 on 2026-05-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ollama_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='bot_deepseek_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Groq API Key'),
        ),
    ]
