# Generated by Django 6.0.5 on 2026-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesettings_bot_deepseek_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон / ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Токен VK-бота'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_link',
            field=models.URLField(default='https://vk.com/im?sel=-your_group_id', verbose_name='Ссылка на VK-бот / сообщество'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_channel',
            field=models.URLField(blank=True, verbose_name='VK-сообщество'),
        ),
    ]
