# Generated by Django 6.0.4 on 2026-04-25 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('case', 'Чехлы'), ('glass', 'Стёкла / плёнки'), ('charger', 'Зарядки / кабели'), ('audio', 'Наушники'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('compatible_with', models.CharField(blank=True, max_length=200, verbose_name='Совместимость')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('min_quantity', models.PositiveIntegerField(default=2, verbose_name='Мин. остаток')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='Мин. остаток (предупреждение)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи / списания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand', verbose_name='Марка')),
                ('phone_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('imei', models.CharField(blank=True, max_length=50, verbose_name='IMEI')),
                ('appearance', models.TextField(blank=True, verbose_name='Внешний вид / комплектация')),
                ('device_password', models.CharField(blank=True, max_length=100, verbose_name='Пароль устройства')),
                ('complaint', models.TextField(blank=True, verbose_name='Жалоба клиента')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('diagnosis', 'Диагностика'), ('waiting_parts', 'Ожидание запчастей'), ('in_progress', 'В работе'), ('done', 'Готов к выдаче'), ('issued', 'Выдан'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предварительная стоимость')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('warranty_days', models.PositiveIntegerField(default=90, verbose_name='Гарантия (дней)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repairs', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.brand', verbose_name='Марка')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repairs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repairs', to='crm.customer', verbose_name='Клиент')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.phonemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Заказ на ремонт',
                'verbose_name_plural': 'Заказы на ремонт',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConditionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('touchscreen', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('front_camera', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('rear_camera', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('speaker_earpiece', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('speaker_loud', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('microphone', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('face_id', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('home_button', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('volume_buttons', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('power_button', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('charging_port', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('wifi', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('bluetooth', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('gps', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('cellular', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('vibration', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('battery', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('nfc', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('body', models.CharField(choices=[('ok', 'Работает'), ('broken', 'Не работает'), ('na', 'Не проверено')], default='na', max_length=10)),
                ('repair_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition_check', to='crm.repairorder')),
            ],
            options={
                'verbose_name': 'Проверка функционала',
            },
        ),
        migrations.CreateModel(
            name='RepairOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за шт.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='crm.repairorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Запчасть в заказе',
                'verbose_name_plural': 'Запчасти в заказе',
            },
        ),
        migrations.CreateModel(
            name='RepairOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название работы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='crm.repairorder')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repairservice')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Имя покупателя')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Завершён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за шт.')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.accessory', verbose_name='Аксессуар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.saleorder')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продажи',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание (ручное)'), ('repair', 'Использовано в ремонте'), ('sale', 'Продажа')], max_length=20, verbose_name='Тип')),
                ('quantity', models.IntegerField(verbose_name='Кол-во (+/-)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='crm.accessory', verbose_name='Аксессуар')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='crm.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'История движений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
