# Generated by Django 6.0.5 on 2026-05-14 11:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_emoji_sitesettings_account_number_and_more'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Аренда'), ('salary', 'Зарплата'), ('parts', 'Закупка запчастей'), ('equipment', 'Оборудование'), ('marketing', 'Маркетинг'), ('utilities', 'Коммунальные'), ('other', 'Прочее')], default='other', max_length=30, verbose_name='Категория')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_new', 'Новый заказ'), ('order_ready', 'Заказ готов'), ('order_overdue', 'Заказ просрочен'), ('low_stock', 'Низкий остаток'), ('comment', 'Комментарий'), ('task', 'Задача'), ('payment', 'Оплата')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Изменение статуса'), ('service_added', 'Добавлена услуга'), ('service_removed', 'Удалена услуга'), ('part_added', 'Добавлена запчасть'), ('part_removed', 'Удалена запчасть'), ('master_assigned', 'Назначен мастер'), ('payment', 'Оплата'), ('comment', 'Комментарий'), ('created', 'Заказ создан')], max_length=30, verbose_name='Событие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('repair', 'Ремонт'), ('sale', 'Продажа'), ('income', 'Приход'), ('expense', 'Расход'), ('salary', 'Зарплата')], default='repair', max_length=20, verbose_name='Тип')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('mixed', 'Смешанная оплата')], default='cash', max_length=20, verbose_name='Метод')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наличные')),
                ('amount_card', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Карта')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('repair_bonus', 'Бонус за ремонт'), ('sale_bonus', 'Бонус за продажу'), ('base_salary', 'Оклад'), ('bonus', 'Премия'), ('penalty', 'Штраф')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('period_year', models.PositiveIntegerField(default=2026, verbose_name='Год')),
                ('period_month', models.PositiveIntegerField(default=5, verbose_name='Месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись зарплаты',
                'verbose_name_plural': 'Зарплатные записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accessory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='part',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка ₽'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка ₽'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('mixed', 'Смешанная оплата')], default='cash', max_length=20, verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accessory_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% с аксессуаров'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Оклад'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='repair_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% с ремонтов'),
        ),
        migrations.AlterField(
            model_name='part',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Мин. остаток'),
        ),
        migrations.AlterField(
            model_name='part',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repairs', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='complaint',
            field=models.TextField(blank=True, verbose_name='Жалоба клиента / неисправность'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repairs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='imei',
            field=models.CharField(blank=True, max_length=50, verbose_name='IMEI / S/N'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('diagnosis', 'Диагностика'), ('waiting_parts', 'Ожидание запчастей'), ('in_progress', 'В работе'), ('approval', 'На согласовании'), ('done', 'Готов к выдаче'), ('issued', 'Выдан'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание (ручное)'), ('repair', 'Использовано в ремонте'), ('sale', 'Продажа'), ('transfer', 'Перемещение'), ('inventory', 'Инвентаризация'), ('return', 'Возврат')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('master', 'Мастер'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='part',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['status'], name='crm_repairo_status_433001_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['created_at'], name='crm_repairo_created_659eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['assigned_to'], name='crm_repairo_assigne_a90ee5_idx'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.repairorder'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='repair_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.repairorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.saleorder', verbose_name='Продажа'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='repair_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.repairorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='repair_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.repairorder', verbose_name='Заказ'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['created_at'], name='crm_payment_created_2914c1_idx'),
        ),
    ]
