# Generated by Django 4.2.16 on 2026-05-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_branch_expense_notification_orderhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceConditionCheck',
        ),
    ]
