# Generated by Django 4.2.16 on 2026-05-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_deviceconditioncheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_new', 'Новый заказ'), ('order_ready', 'Заказ готов'), ('order_overdue', 'Заказ просрочен'), ('low_stock', 'Низкий остаток'), ('comment', 'Комментарий'), ('task', 'Задача'), ('payment', 'Оплата'), ('penalty', 'Штраф')], max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('device', models.CharField(blank=True, max_length=200, verbose_name='Устройство')),
                ('problem', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Желаемое время')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('crm', 'CRM'), ('telegram', 'Telegram'), ('website', 'Сайт')], default='crm', max_length=20, verbose_name='Источник')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram chat ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания (внутренние)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_appointment', to='crm.repairorder', verbose_name='Созданный заказ')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
