# Generated by Django 4.2.16 on 2026-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_appointment_and_bot_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Telegram ID'),
        ),
    ]
