# Generated by Django 6.0.5 on 2026-05-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_customer_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки (только для админа)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
