# Generated by Django 4.2.16 on 2026-05-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_repair_order_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='staff_profiles', to='crm.branch', verbose_name='Доступные филиалы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_employees', to='crm.branch', verbose_name='Активный филиал сегодня'),
        ),
    ]
