# Generated by Django 6.0.5 on 2026-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customer_pd_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('crm', 'CRM'), ('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('website', 'Сайт')], default='crm', max_length=20, verbose_name='Источник'),
        ),
    ]
