# Generated by Django 6.0.5 on 2026-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_vk_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='VK user ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='VK ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='ВКонтакте'),
        ),
    ]
